#!/usr/bin/env node
/**
 * recover-keys.js
 *
 * Break-glass recovery for the age identity key generated by
 * setup-keys.js (issue #108: "No break-glass recovery path"). Two
 * independent recovery paths, matching whichever setup-keys.js was run
 * with:
 *
 *   1. Shamir shares (--from-shares <path> <path> ...): reconstructs the
 *      original age identity file from any --shamir-threshold (or more)
 *      of the shares setup-keys.js generated. Combining MORE than the
 *      threshold is harmless (sss.combine() only needs `threshold` of
 *      them, extra shares are ignored); combining FEWER produces garbage,
 *      not a clear error -- see the verification step below, which is
 *      why this script always verifies the reconstructed identity
 *      actually round-trips through age itself before writing it out.
 *
 *   2. QR code (--from-qr <path-to-decoded-text-file>): if the operator
 *      scanned the QR code setup-keys.js generated with an external QR
 *      reader (this script does not decode images itself -- see "Why no
 *      image decoding" below) and saved the resulting text, this
 *      restores the identity file directly from that text.
 *
 * This script never talks to the network and never requires the bot to
 * be running. It only needs the `age` binary (to verify the
 * reconstructed identity is valid) and, for the Shamir path, the
 * `shamirs-secret-sharing` npm package already used by setup-keys.js.
 *
 * Why no image decoding: adding a QR-decoding-from-image dependency
 * (camera/image-processing libraries) to a break-glass recovery tool
 * that must work in a genuine emergency, possibly years after this
 * dependency last received a security update, is a real, unnecessary
 * risk for a problem operators can already solve with any phone's
 * built-in camera app or a dedicated QR reader -- decode elsewhere,
 * paste the resulting text into a file, and point this script at that
 * file.
 *
 * Usage:
 *   node scripts/recover-keys.js --from-shares <share1> <share2> [...] --output <path>
 *   node scripts/recover-keys.js --from-qr <decoded-text-file> --output <path>
 *
 * On success, writes a valid age identity file to --output (mode 0400)
 * and prints its public key so the operator can confirm it matches the
 * one setup-keys.js originally reported (a real, if unlikely, way this
 * could still go wrong: combining shares from two DIFFERENT identities
 * by mistake produces a file that looks superficially valid but is not
 * the one any existing KEK was actually encrypted to).
 */

import { execFileSync } from "node:child_process";
import { pathToFileURL } from "node:url";
import { existsSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import sss from "shamirs-secret-sharing";

export function parseArgs(argv) {
  const args = { mode: null, shares: [], qrFile: null, output: null };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--from-shares") {
      args.mode = "shamir";
      while (argv[i + 1] && !argv[i + 1].startsWith("--")) {
        args.shares.push(argv[++i]);
      }
    } else if (arg === "--from-qr") {
      args.mode = "qr";
      args.qrFile = argv[++i];
    } else if (arg === "--output") {
      args.output = argv[++i];
    } else if (arg === "--help" || arg === "-h") {
      printUsage();
      process.exit(0);
    }
  }
  if (!args.mode) {
    console.error("One of --from-shares or --from-qr is required.\n");
    printUsage();
    process.exit(2);
  }
  if (args.mode === "shamir" && args.shares.length < 2) {
    console.error(`--from-shares requires at least 2 share file paths (got ${args.shares.length}). The exact number needed depends on the --shamir-threshold used when the shares were generated.`);
    process.exit(2);
  }
  if (!args.output) {
    console.error("--output <path> is required (where to write the recovered age identity file).");
    process.exit(2);
  }
  if (existsSync(args.output)) {
    console.error(`Refusing to overwrite an existing file at --output: ${args.output}`);
    process.exit(1);
  }
  return args;
}

function printUsage() {
  console.log(`Usage:
  node scripts/recover-keys.js --from-shares <share1> <share2> [...] --output <path>
  node scripts/recover-keys.js --from-qr <decoded-text-file> --output <path>
`);
}

export function reconstructFromShares(sharePaths) {
  const shares = sharePaths.map((p) => {
    const hex = readFileSync(p, "utf8").trim();
    if (!/^[0-9a-f]+$/i.test(hex)) {
      throw new Error(`Share file ${p} does not look like a hex-encoded share written by setup-keys.js.`);
    }
    return Buffer.from(hex, "hex");
  });
  const combined = sss.combine(shares);
  return combined.toString("utf8");
}

export function reconstructFromQR(qrTextFile) {
  return readFileSync(qrTextFile, "utf8");
}

export function verifyIdentity(identityText, outputPath) {
  // Round-trip verification: a reconstructed identity from too-few or
  // mismatched Shamir shares does not throw, it silently produces the
  // WRONG secret (sss.combine()'s own documented behavior: "will not
  // throw an error for incorrect shares"). The only reliable check is
  // to actually exercise the candidate identity with age itself --
  // encrypt a known value to its claimed public key, then decrypt with
  // the candidate identity, and confirm the round-trip matches.
  //
  // Nothing is written to outputPath until AFTER the public-key-line
  // check below passes -- a garbage reconstruction (wrong/too-few
  // shares) must leave no file behind at all, not a file that gets
  // wiped only in the round-trip-failure branch further down.
  const publicKeyLine = identityText.split("\n").find((line) => line.startsWith("# public key:"));
  const publicKey = publicKeyLine ? publicKeyLine.replace("# public key:", "").trim() : null;
  if (!publicKey) {
    throw new Error("Reconstructed identity does not contain a recognizable '# public key:' line -- this is not a valid age identity file. Check that you used the correct shares/QR text and the right threshold.");
  }
  writeFileSync(outputPath, identityText, { mode: 0o400 });

  const probe = `recover-keys-verification-${Date.now()}`;
  const probeEncPath = `${outputPath}.verify.age`;
  try {
    execFileSync("age", ["-r", publicKey, "-o", probeEncPath], { input: probe });
    const decrypted = execFileSync("age", ["--decrypt", "-i", outputPath, probeEncPath], { encoding: "utf8" }).trim();
    if (decrypted !== probe) {
      throw new Error("round-trip mismatch");
    }
  } catch (error) {
    try { writeFileSync(outputPath, ""); } catch {}
    throw new Error(
      `The reconstructed identity failed a real encrypt/decrypt round-trip test -- it is NOT a valid, usable age identity. ` +
      `This usually means too few shares were combined, the shares are from different identities, or the QR text was ` +
      `transcribed incorrectly. Nothing was written to ${outputPath}. (${error.message})`
    );
  } finally {
    try { execFileSync("rm", ["-f", probeEncPath]); } catch {}
  }

  return publicKey;
}

function main() {
  const args = parseArgs(process.argv.slice(2));

  let identityText;
  if (args.mode === "shamir") {
    console.log(`Reconstructing age identity from ${args.shares.length} share(s)...`);
    identityText = reconstructFromShares(args.shares);
  } else {
    console.log(`Reading age identity from decoded QR text: ${args.qrFile}`);
    identityText = reconstructFromQR(args.qrFile);
  }

  console.log("Verifying the reconstructed identity with a real age encrypt/decrypt round-trip...");
  const publicKey = verifyIdentity(identityText, args.output);
  chmodSync(args.output, 0o400);

  console.log(`\nRecovery succeeded. Age identity written to: ${args.output} (mode 0400)`);
  console.log(`Public key: ${publicKey}`);
  console.log("\nConfirm this matches the public key setup-keys.js originally reported before trusting this identity for any existing KEK. If it does not match, you have reconstructed a DIFFERENT identity than the one your KEK was encrypted to -- do not use it.");
  console.log(`\nTo use this recovered identity, set ACP_AGE_IDENTITY_FILE=${args.output} and restart the bot.`);
}

// Guarded so this file can be imported for direct unit testing of the
// exported functions above without also running the full CLI flow --
// matches this repo's own established pattern (see reencrypt-secrets.js).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    main();
  } catch (error) {
    console.error(`recover-keys.js failed: ${error.message}`);
    process.exit(1);
  }
}
