/**
 * Phase 3: Registry Loader & Manager
 * 
 * Loads commands-registry.json at startup and provides dynamic refresh.
 * The registry is generated by Phase 2 (scripts/generate-command-registry.js)
 * and committed to the repo. Phase 3 loads and uses it at runtime.
 * 
 * Supports:
 * - Loading registry from disk at startup
 * - In-memory caching with validation
 * - Atomic refresh via promise-based singleton to prevent race conditions
 * - Full refresh from Core's catalog endpoint (adapterClient.discordCatalog())
 *   with a 4h staleness-monitoring window (not true HTTP conditional GET --
 *   see refreshRegistryFromCore()'s own comment for why)
 * - Schema validation on all registry loads
 * 
 * Tracked by yacketrj/arrakis-control-panel#181 (Phase 3 runtime loading)
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createHmac } from "node:crypto";
import { logInfo, logError } from "./logger.js";
import { transformCatalogToRegistry, applyCommandOverrides } from "./catalogTransform.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

// In-memory registry cache with thread-safety
let cachedRegistry = null;
let registryLoadTime = null;
// etagExpireTime: staleness bookkeeping only (logging/monitoring), not a
// real HTTP ETag -- see refreshRegistryFromCore()'s scope note on why
// true conditional-GET isn't implemented against adapterClient.request().
let etagExpireTime = null;
let refreshInProgress = null; // Prevents concurrent refresh calls
let registrySignature = null; // SEC-1: Track signature for tampering detection

const ETAG_TTL_MS = 4 * 60 * 60 * 1000; // SEC-3 FIX: Reduced from 24h to 4h; staleness TTL
const REGISTRY_CONTENT_HASH_KEY = "DUNE_REGISTRY_HASH_KEY"; // Used for HMAC validation

/**
 * BUG FIX (2026-08-19, found via test/registryLoader.test.js's own
 * "verifies signature when Core provides one" test): the signature MUST
 * be computed over the registry payload WITHOUT its own `signature`
 * field. The original implementation hashed the full JSON (signature
 * field included), which is circular -- a signer can never know its own
 * output signature in advance, so no real signature could ever verify
 * successfully. This went unnoticed because the local committed
 * registry file never has a `signature` field (hasSig: false in every
 * production log), so verifyRegistrySignature() was never actually
 * exercised with a real signature until this test existed.
 *
 * canonicalRegistryJson() strips `signature` before serializing, on
 * both the signing side (hypothetical -- awaits Core producing
 * signatures) and the verification side, so they operate on the exact
 * same byte-for-byte payload.
 */
function canonicalRegistryJson(registry) {
  const { signature, ...unsigned } = registry || {};
  return JSON.stringify(unsigned);
}

/**
 * SEC-1 FIX: Compute HMAC-SHA256 signature of registry content
 * Used to detect tampering and validate origin
 */
function computeRegistrySignature(registryJson) {
  // Use a fixed key for local/committed registries
  // In production, this would use a key from config or Core
  const key = process.env.REGISTRY_SIGNATURE_KEY || REGISTRY_CONTENT_HASH_KEY;
  return createHmac("sha256", key).update(registryJson).digest("hex");
}

/**
 * SEC-1 FIX: Verify registry signature before accepting it
 * Prevents MITM attacks and file tampering
 * `registryJson` MUST already exclude the `signature` field (see
 * canonicalRegistryJson() above) -- callers pass the canonical form,
 * never the raw signed payload.
 */
function verifyRegistrySignature(registryJson, providedSignature) {
  const expectedSignature = computeRegistrySignature(registryJson);
  
  if (!providedSignature) {
    // For local registries, signature is optional (file system is secure)
    logInfo("registry.signature_validation_skipped", { reason: "no_signature_provided" });
    return true;
  }
  
  // Constant-time comparison to prevent timing attacks
  const matches = providedSignature.length === expectedSignature.length &&
    [...providedSignature].every((char, idx) => char === expectedSignature[idx]);
  
  if (!matches) {
    throw new Error(`Registry signature verification failed. Possible tampering detected.`);
  }
  
  return true;
}

/**
 * Validate registry structure before use
 * SEC-4 FIX: Validate command names against Discord constraints
 * Throws if registry is malformed
 * Exported (not just internal) so test/registryLoader.test.js can verify
 * validation behavior directly instead of only indirectly via
 * loadRegistryAtStartup()/refreshRegistryFromCore() -- see TEST-1 in the
 * Phase 3 audit remediation.
 */
export function validateRegistry(registry) {
  if (!registry || typeof registry !== "object") {
    throw new Error("Registry must be an object");
  }
  if (!Array.isArray(registry.groups)) {
    throw new Error("Registry.groups must be an array");
  }
  if (typeof registry.version !== "number") {
    throw new Error("Registry.version must be a number");
  }
  
  // SEC-3 FIX: Validate registry size to prevent DoS
  if (registry.groups.length > 25) {
    throw new Error("Registry cannot have more than 25 command groups (Discord limit)");
  }
  
  // Validate group structure
  for (const group of registry.groups) {
    if (!group.name || typeof group.name !== "string") {
      throw new Error(`Group missing or invalid name: ${JSON.stringify(group)}`);
    }
    
    // SEC-4 FIX: Validate group name matches Discord constraints
    if (!/^[a-z0-9_-]{1,32}$/.test(group.name.toLowerCase())) {
      throw new Error(`Group name "${group.name}" violates Discord naming constraints (a-z, 0-9, _, -, 1-32 chars)`);
    }
    
    if (!Array.isArray(group.subcommands)) {
      throw new Error(`Group "${group.name}" subcommands must be an array`);
    }
    
    if (group.subcommands.length > 25) {
      throw new Error(`Group "${group.name}" cannot have more than 25 subcommands (Discord limit)`);
    }
    
    // Validate subcommand structure
    for (const sc of group.subcommands) {
      if (!sc.name || typeof sc.name !== "string") {
        throw new Error(`Subcommand in group "${group.name}" missing or invalid name`);
      }
      
      // SEC-4 FIX: Validate subcommand name
      if (!/^[a-z0-9_-]{1,32}$/.test(sc.name.toLowerCase())) {
        throw new Error(`Subcommand "${sc.name}" violates Discord naming constraints`);
      }
      
      if (typeof sc.description !== "string") {
        throw new Error(`Subcommand "${sc.name}" description must be a string`);
      }
      
      // SEC-5 FIX: Validate params if present
      if (sc.params && Array.isArray(sc.params)) {
        for (const param of sc.params) {
          if (!param.name || typeof param.name !== "string") {
            throw new Error(`Parameter in subcommand "${sc.name}" missing name`);
          }
          if (!/^[a-z0-9_]{1,32}$/.test(param.name.toLowerCase())) {
            throw new Error(`Parameter name "${param.name}" violates Discord constraints`);
          }
        }
      }
    }
  }
  
  return true;
}

/**
 * Load src/commandOverrides.json for use during a runtime refresh.
 * Best-effort: an operator-editable file going missing/malformed
 * should not break /dune admin sync-commands entirely -- falls back to
 * no overrides (Core's raw names/tiers) and logs why, rather than
 * throwing and discarding an otherwise-valid refresh.
 */
function loadOverridesForRefresh() {
  try {
    const overridesPath = join(repoRoot, "src", "commandOverrides.json");
    return JSON.parse(readFileSync(overridesPath, "utf8"));
  } catch (error) {
    logInfo("registry.overrides_load_failed_during_refresh", {
      note: "Proceeding without bot-side overrides (exclude/rename/retier) for this refresh.",
      error: error.message
    });
    return {};
  }
}

/**
 * Load commands-registry.json from disk at startup
 * SEC-1 FIX: Validates structure AND signature
 * Validates registry structure before caching
 * This is a MANDATORY startup step - bot will not start without a valid registry
 */
export function loadRegistryAtStartup() {
  try {
    const registryPath = join(repoRoot, "src", "commands-registry.json");
    const registryJson = readFileSync(registryPath, "utf8");
    const registry = JSON.parse(registryJson);
    
    // SEC-1: Verify signature if present (for remotely fetched registries).
    // Must hash the canonical (signature-excluded) form, not the raw file
    // text -- see canonicalRegistryJson()'s comment for why.
    if (registry.signature) {
      verifyRegistrySignature(canonicalRegistryJson(registry), registry.signature);
    }
    
    // Validate structure before caching
    validateRegistry(registry);
    
    cachedRegistry = registry;
    registryLoadTime = new Date();
    etagExpireTime = new Date(Date.now() + ETAG_TTL_MS);
    registrySignature = registry.signature || null;
    
    logInfo("registry.loaded_at_startup", {
      groups: cachedRegistry.groups?.length || 0,
      commands: cachedRegistry.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0,
      version: cachedRegistry.version,
      hasSig: !!registry.signature,
      timestamp: registryLoadTime.toISOString()
    });
    
    return cachedRegistry;
  } catch (error) {
    logError("registry.load_failed", error);
    throw new Error(`Failed to load command registry: ${error.message}`);
  }
}

/**
 * Get the currently cached registry
 * Throws if registry hasn't been loaded yet
 */
export function getRegistryFromCache() {
  if (!cachedRegistry) {
    const err = new Error("Registry not loaded. Call loadRegistryAtStartup() first.");
    logError("registry.cache_miss", err);
    throw err;
  }
  return cachedRegistry;
}

/**
 * Refresh registry from Core's catalog endpoint
 * - Atomic: uses promise-based singleton to prevent concurrent mutations
 * - Validates new registry before caching
 * - Always performs a full fetch (see note below on conditional GET)
 *
 * CORRECTNESS FIX (2026-08-19, found during live E2E testing): the
 * previous implementation called
 * `adapterClient.request(guildId, { method, path, headers })` -- but
 * AdapterClient.request()'s real signature is
 * `request(route, actor, extra, guildId)`, where `route` is looked up
 * in a named-route table (cfg.adapter.paths[route]), not an arbitrary
 * path string. That meant `guildId` was being passed as `route`,
 * which is never a valid key, so every single call failed with
 * "Unsupported adapter route: <guildId>" -- unconditionally, whether
 * or not Core was actually reachable. This was never caught by the
 * Layer 2 desk-review audits (Architecture/Security/QA) because none
 * of them traced the actual call into adapterClient.js to verify the
 * interface matched; it surfaced only during live Discord E2E testing.
 *
 * Fix: use the real, named "discord-catalog" route (added to
 * config.js's DEFAULT_PATHS/DEFAULT_METHODS) via the new
 * adapterClient.discordCatalog(actor, guildId) convenience method,
 * matching the exact pattern every other route in this file already
 * uses (see linkAccountViaSteam(), playerAccountsList(), etc.).
 *
 * SCOPE NOTE on ETag/conditional-GET: AdapterClient.request() does not
 * currently support passing custom request headers on GET, nor does
 * it expose response status/headers to the caller on success (it
 * returns only the parsed body, and throws AdapterHttpError with a
 * `.status` on any non-2xx, which includes 304 and 412). Rather than
 * half-implement conditional GET against an interface that doesn't
 * support it, this always performs a full fetch. Local TTL-based
 * staleness bookkeeping (etagExpireTime) is retained for monitoring/
 * logging purposes only -- it no longer drives actual HTTP-level
 * conditional requests. True conditional GET would require extending
 * AdapterClient.request() itself (a shared, sensitive code path used
 * by every command), which is intentionally out of scope for this fix.
 */
export async function refreshRegistryFromCore(adapterClient, actor, guildId) {
  // CRITICAL-1 FIX: Queue refreshes to prevent race condition
  // If refresh is already in progress, wait for it instead of starting another
  if (refreshInProgress) {
    return refreshInProgress;
  }

  refreshInProgress = (async () => {
    try {
      // Staleness bookkeeping only (see scope note above) -- logged,
      // not used to skip the fetch.
      if (etagExpireTime && new Date() > etagExpireTime) {
        logInfo("registry.etag_expired", { expiredAt: etagExpireTime.toISOString() });
        etagExpireTime = null;
      }

      const rawResponse = await adapterClient.discordCatalog(actor, guildId);

      // SEC-1: Verify signature if Core provided one in the payload.
      // Canonical (signature-excluded) form -- see canonicalRegistryJson().
      // Checked on the raw response, before transform/override, since
      // that's the exact byte-for-byte payload Core would have signed.
      if (rawResponse?.signature) {
        verifyRegistrySignature(canonicalRegistryJson(rawResponse), rawResponse.signature);
      } else {
        logInfo("registry.refresh_no_signature", {
          note: "Core did not provide a signature. Proceeding without signature verification (MITM risk)."
        });
      }

      // CORRECTNESS FIX (2026-08-20): Core's raw response is
      // { ok, protocolVersion, catalog: { version, groups } } with v2
      // subcommands shaped { name, routes: [...] } -- transform to the
      // bot's flat internal shape before validating/caching. See
      // catalogTransform.js's own module comment for the full
      // root-cause writeup (found via live E2E testing).
      const transformed = transformCatalogToRegistry(rawResponse);
      const newRegistry = applyCommandOverrides(transformed, loadOverridesForRefresh());

      // HIGH-3 FIX: Validate registry before caching
      validateRegistry(newRegistry);

      cachedRegistry = newRegistry;
      registryLoadTime = new Date();
      etagExpireTime = new Date(Date.now() + ETAG_TTL_MS);
      registrySignature = newRegistry.signature || null;

      logInfo("registry.refreshed_from_core", {
        groups: newRegistry.groups?.length || 0,
        commands: newRegistry.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0,
        version: newRegistry.version,
        etagExpiresAt: etagExpireTime?.toISOString() || "none",
        signatureVerified: !!registrySignature,
        timestamp: registryLoadTime.toISOString()
      });

      return newRegistry;
    } catch (error) {
      // Surface Core's real HTTP status (if any) in the internal log
      // without leaking it to the end user (see SEC-2 sanitization in
      // commands.js's syncCommandsPayload()).
      logError("registry.refresh_failed", error, { status: error?.status });
      throw new Error(`Failed to refresh registry from Core: ${error.message}`);
    } finally {
      // Clear the refresh lock
      refreshInProgress = null;
    }
  })();

  return refreshInProgress;
}

/**
 * Convert registry format to Discord slash command format
 * Used by buildDuneCommand() Phase 3 integration
 * MEDIUM-3 FIX: Add defensive checks for null/undefined values
 */
export function registryToDiscordFormat(registry) {
  if (!registry || !registry.groups) {
    return { toJSON: () => [] };
  }

  const commands = [];

  for (const group of registry.groups) {
    // Defensive: skip if group name is missing
    if (!group.name) {
      logError("registry.invalid_group", { group });
      continue;
    }

    const subcommands = (group.subcommands || []).map((sc) => {
      // Defensive: skip if subcommand name is missing
      if (!sc.name) {
        logError("registry.invalid_subcommand", { group: group.name, sc });
        return null;
      }

      return {
        name: sc.name.toLowerCase().replace(/\s+/g, "-"),
        description: sc.description || "No description",
        options: (sc.params || []).map((param) => {
          // Defensive: skip if param name is missing
          if (!param.name) {
            logError("registry.invalid_param", { group: group.name, subcommand: sc.name, param });
            return null;
          }

          return {
            name: param.name.toLowerCase(),
            description: param.description || "Parameter",
            type: 3, // STRING type
            required: param.required !== false
          };
        }).filter(Boolean) // Remove null entries
      };
    }).filter(Boolean); // Remove null entries

    if (subcommands.length > 0) {
      commands.push({
        name: group.name.toLowerCase(),
        description: group.title || "Command group",
        type: 1, // CHAT_INPUT
        options: subcommands.map((sc) => ({
          name: sc.name,
          description: sc.description,
          type: 1, // SUBCOMMAND
          options: sc.options
        }))
      });
    }
  }

  return {
    toJSON: () => commands
  };
}

/**
 * Get registry metadata (load time, staleness window, signature verification, etc.)
 */
export function getRegistryMetadata() {
  return {
    loadTime: registryLoadTime,
    version: cachedRegistry?.version,
    groups: cachedRegistry?.groups?.length || 0,
    etagExpiresAt: etagExpireTime?.toISOString(),
    signatureVerified: !!registrySignature,
    commandCount: cachedRegistry?.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0
  };
}

/**
 * Test-only: reset all module-level state.
 * Not used by production code paths -- exists solely so
 * test/registryLoader.test.js can start each test from a clean slate
 * instead of leaking cache/lock state across tests in the same process.
 */
export function __resetForTests() {
  cachedRegistry = null;
  registryLoadTime = null;
  etagExpireTime = null;
  refreshInProgress = null;
  registrySignature = null;
}

