/**
 * Phase 3: Registry Loader & Manager
 * 
 * Loads commands-registry.json at startup and provides dynamic refresh.
 * The registry is generated by Phase 2 (scripts/generate-command-registry.js)
 * and committed to the repo. Phase 3 loads and uses it at runtime.
 * 
 * Supports:
 * - Loading registry from disk at startup
 * - In-memory caching with validation
 * - Atomic refresh via promise-based singleton to prevent race conditions
 * - ETag-based refresh from Core's catalog endpoint with 24h expiration
 * - Schema validation on all registry loads
 * 
 * Tracked by yacketrj/arrakis-control-panel#181 (Phase 3 runtime loading)
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createHmac } from "node:crypto";
import { logInfo, logError } from "./logger.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

// In-memory registry cache with thread-safety
let cachedRegistry = null;
let registryLoadTime = null;
let etag = null;
let etagExpireTime = null;
let refreshInProgress = null; // Prevents concurrent refresh calls
let registrySignature = null; // SEC-1: Track signature for tampering detection

const ETAG_TTL_MS = 4 * 60 * 60 * 1000; // SEC-3 FIX: Reduced from 24h to 4h
const REGISTRY_CONTENT_HASH_KEY = "DUNE_REGISTRY_HASH_KEY"; // Used for HMAC validation

/**
 * SEC-1 FIX: Compute HMAC-SHA256 signature of registry content
 * Used to detect tampering and validate origin
 */
function computeRegistrySignature(registryJson) {
  // Use a fixed key for local/committed registries
  // In production, this would use a key from config or Core
  const key = process.env.REGISTRY_SIGNATURE_KEY || REGISTRY_CONTENT_HASH_KEY;
  return createHmac("sha256", key).update(registryJson).digest("hex");
}

/**
 * SEC-1 FIX: Verify registry signature before accepting it
 * Prevents MITM attacks and file tampering
 */
function verifyRegistrySignature(registryJson, providedSignature) {
  const expectedSignature = computeRegistrySignature(registryJson);
  
  if (!providedSignature) {
    // For local registries, signature is optional (file system is secure)
    logInfo("registry.signature_validation_skipped", { reason: "no_signature_provided" });
    return true;
  }
  
  // Constant-time comparison to prevent timing attacks
  const matches = providedSignature.length === expectedSignature.length &&
    [...providedSignature].every((char, idx) => char === expectedSignature[idx]);
  
  if (!matches) {
    throw new Error(`Registry signature verification failed. Possible tampering detected.`);
  }
  
  return true;
}

/**
 * Validate registry structure before use
 * SEC-4 FIX: Validate command names against Discord constraints
 * Throws if registry is malformed
 */
function validateRegistry(registry) {
  if (!registry || typeof registry !== "object") {
    throw new Error("Registry must be an object");
  }
  if (!Array.isArray(registry.groups)) {
    throw new Error("Registry.groups must be an array");
  }
  if (typeof registry.version !== "number") {
    throw new Error("Registry.version must be a number");
  }
  
  // SEC-3 FIX: Validate registry size to prevent DoS
  if (registry.groups.length > 25) {
    throw new Error("Registry cannot have more than 25 command groups (Discord limit)");
  }
  
  // Validate group structure
  for (const group of registry.groups) {
    if (!group.name || typeof group.name !== "string") {
      throw new Error(`Group missing or invalid name: ${JSON.stringify(group)}`);
    }
    
    // SEC-4 FIX: Validate group name matches Discord constraints
    if (!/^[a-z0-9_-]{1,32}$/.test(group.name.toLowerCase())) {
      throw new Error(`Group name "${group.name}" violates Discord naming constraints (a-z, 0-9, _, -, 1-32 chars)`);
    }
    
    if (!Array.isArray(group.subcommands)) {
      throw new Error(`Group "${group.name}" subcommands must be an array`);
    }
    
    if (group.subcommands.length > 25) {
      throw new Error(`Group "${group.name}" cannot have more than 25 subcommands (Discord limit)`);
    }
    
    // Validate subcommand structure
    for (const sc of group.subcommands) {
      if (!sc.name || typeof sc.name !== "string") {
        throw new Error(`Subcommand in group "${group.name}" missing or invalid name`);
      }
      
      // SEC-4 FIX: Validate subcommand name
      if (!/^[a-z0-9_-]{1,32}$/.test(sc.name.toLowerCase())) {
        throw new Error(`Subcommand "${sc.name}" violates Discord naming constraints`);
      }
      
      if (typeof sc.description !== "string") {
        throw new Error(`Subcommand "${sc.name}" description must be a string`);
      }
      
      // SEC-5 FIX: Validate params if present
      if (sc.params && Array.isArray(sc.params)) {
        for (const param of sc.params) {
          if (!param.name || typeof param.name !== "string") {
            throw new Error(`Parameter in subcommand "${sc.name}" missing name`);
          }
          if (!/^[a-z0-9_]{1,32}$/.test(param.name.toLowerCase())) {
            throw new Error(`Parameter name "${param.name}" violates Discord constraints`);
          }
        }
      }
    }
  }
  
  return true;
}

/**
 * Load commands-registry.json from disk at startup
 * SEC-1 FIX: Validates structure AND signature
 * Validates registry structure before caching
 * This is a MANDATORY startup step - bot will not start without a valid registry
 */
export function loadRegistryAtStartup() {
  try {
    const registryPath = join(repoRoot, "src", "commands-registry.json");
    const registryJson = readFileSync(registryPath, "utf8");
    const registry = JSON.parse(registryJson);
    
    // SEC-1: Verify signature if present (for remotely fetched registries)
    if (registry.signature) {
      verifyRegistrySignature(registryJson, registry.signature);
    }
    
    // Validate structure before caching
    validateRegistry(registry);
    
    cachedRegistry = registry;
    registryLoadTime = new Date();
    etagExpireTime = new Date(Date.now() + ETAG_TTL_MS);
    registrySignature = registry.signature || null;
    
    logInfo("registry.loaded_at_startup", {
      groups: cachedRegistry.groups?.length || 0,
      commands: cachedRegistry.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0,
      version: cachedRegistry.version,
      hasSig: !!registry.signature,
      timestamp: registryLoadTime.toISOString()
    });
    
    return cachedRegistry;
  } catch (error) {
    logError("registry.load_failed", error);
    throw new Error(`Failed to load command registry: ${error.message}`);
  }
}

/**
 * Get the currently cached registry
 * Throws if registry hasn't been loaded yet
 */
export function getRegistryFromCache() {
  if (!cachedRegistry) {
    const err = new Error("Registry not loaded. Call loadRegistryAtStartup() first.");
    logError("registry.cache_miss", err);
    throw err;
  }
  return cachedRegistry;
}

/**
 * Refresh registry from Core's catalog endpoint
 * - Atomic: uses promise-based singleton to prevent concurrent mutations
 * - Validates new registry before caching
 * - Supports ETag-based conditional requests with 24h expiration
 * - Handles 412 (Precondition Failed) by clearing stale ETag
 */
export async function refreshRegistryFromCore(adapterClient, guildId) {
  // CRITICAL-1 FIX: Queue refreshes to prevent race condition
  // If refresh is already in progress, wait for it instead of starting another
  if (refreshInProgress) {
    return refreshInProgress;
  }

  refreshInProgress = (async () => {
    try {
      // Check if ETag has expired
      if (etagExpireTime && new Date() > etagExpireTime) {
        logInfo("registry.etag_expired", { expiredAt: etagExpireTime.toISOString() });
        etag = null; // Clear stale ETag
        etagExpireTime = null;
      }

      const response = await adapterClient.request(guildId, {
        method: "GET",
        path: "/api/integrations/discord/catalog",
        headers: etag ? { "If-None-Match": etag } : {}
      });

      if (response.status === 304) {
        // Not modified - refresh ETag expiry
        etagExpireTime = new Date(Date.now() + ETAG_TTL_MS);
        logInfo("registry.refresh_not_modified", {
          etag,
          expiresAt: etagExpireTime.toISOString(),
          timestamp: new Date().toISOString()
        });
        return cachedRegistry;
      }

      // HIGH-2 FIX: Handle 412 Precondition Failed (stale ETag)
      if (response.status === 412) {
        logInfo("registry.etag_invalid", { 
          stalEtag: etag,
          timestamp: new Date().toISOString()
        });
        etag = null;
        etagExpireTime = null;
        throw new Error("ETag validation failed. Retry sync-commands to fetch fresh registry.");
      }

      if (response.status !== 200) {
        throw new Error(`Core returned ${response.status}`);
      }

      const newRegistry = response.data;
      
      // SEC-1 FIX: Verify Core's response signature before trusting it
      if (response.headers?.["x-registry-signature"]) {
        const registryJson = JSON.stringify(newRegistry);
        verifyRegistrySignature(registryJson, response.headers["x-registry-signature"]);
      } else {
        logInfo("registry.refresh_no_signature", {
          note: "Core did not provide X-Registry-Signature header. Proceeding without signature verification (MITM risk)."
        });
      }
      
      // HIGH-3 FIX: Validate registry before caching
      validateRegistry(newRegistry);

      // Update ETag if provided
      if (response.headers?.etag) {
        etag = response.headers.etag;
        etagExpireTime = new Date(Date.now() + ETAG_TTL_MS);
      }

      cachedRegistry = newRegistry;
      registryLoadTime = new Date();
      registrySignature = newRegistry.signature || null;

      logInfo("registry.refreshed_from_core", {
        groups: newRegistry.groups?.length || 0,
        commands: newRegistry.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0,
        version: newRegistry.version,
        etag: etag || "none",
        etagExpiresAt: etagExpireTime?.toISOString() || "none",
        signatureVerified: !!registrySignature,
        timestamp: registryLoadTime.toISOString()
      });

      return newRegistry;
    } catch (error) {
      logError("registry.refresh_failed", error);
      throw new Error(`Failed to refresh registry from Core: ${error.message}`);
    } finally {
      // Clear the refresh lock
      refreshInProgress = null;
    }
  })();

  return refreshInProgress;
}

/**
 * Convert registry format to Discord slash command format
 * Used by buildDuneCommand() Phase 3 integration
 * MEDIUM-3 FIX: Add defensive checks for null/undefined values
 */
export function registryToDiscordFormat(registry) {
  if (!registry || !registry.groups) {
    return { toJSON: () => [] };
  }

  const commands = [];

  for (const group of registry.groups) {
    // Defensive: skip if group name is missing
    if (!group.name) {
      logError("registry.invalid_group", { group });
      continue;
    }

    const subcommands = (group.subcommands || []).map((sc) => {
      // Defensive: skip if subcommand name is missing
      if (!sc.name) {
        logError("registry.invalid_subcommand", { group: group.name, sc });
        return null;
      }

      return {
        name: sc.name.toLowerCase().replace(/\s+/g, "-"),
        description: sc.description || "No description",
        options: (sc.params || []).map((param) => {
          // Defensive: skip if param name is missing
          if (!param.name) {
            logError("registry.invalid_param", { group: group.name, subcommand: sc.name, param });
            return null;
          }

          return {
            name: param.name.toLowerCase(),
            description: param.description || "Parameter",
            type: 3, // STRING type
            required: param.required !== false
          };
        }).filter(Boolean) // Remove null entries
      };
    }).filter(Boolean); // Remove null entries

    if (subcommands.length > 0) {
      commands.push({
        name: group.name.toLowerCase(),
        description: group.title || "Command group",
        type: 1, // CHAT_INPUT
        options: subcommands.map((sc) => ({
          name: sc.name,
          description: sc.description,
          type: 1, // SUBCOMMAND
          options: sc.options
        }))
      });
    }
  }

  return {
    toJSON: () => commands
  };
}

/**
 * Get registry metadata (load time, ETag, signature verification, etc.)
 */
export function getRegistryMetadata() {
  return {
    loadTime: registryLoadTime,
    version: cachedRegistry?.version,
    groups: cachedRegistry?.groups?.length || 0,
    etag,
    etagExpiresAt: etagExpireTime?.toISOString(),
    signatureVerified: !!registrySignature,
    commandCount: cachedRegistry?.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0
  };
}

