/**
 * Phase 3: Registry Loader & Manager
 * 
 * Loads commands-registry.json at startup and provides dynamic refresh.
 * The registry is generated by Phase 2 (scripts/generate-command-registry.js)
 * and committed to the repo. Phase 3 loads and uses it at runtime.
 * 
 * Supports:
 * - Loading registry from disk at startup
 * - In-memory caching
 * - Dynamic refresh via /dune admin sync-commands
 * - ETag-based refresh from Core's catalog endpoint
 * 
 * Tracked by yacketrj/arrakis-control-panel#181 (Phase 3 runtime loading)
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { logInfo, logError } from "./logger.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

// In-memory registry cache
let cachedRegistry = null;
let registryLoadTime = null;
let etag = null;

/**
 * Load commands-registry.json from disk at startup
 */
export function loadRegistryAtStartup() {
  try {
    const registryPath = join(repoRoot, "src", "commands-registry.json");
    const registryJson = readFileSync(registryPath, "utf8");
    cachedRegistry = JSON.parse(registryJson);
    registryLoadTime = new Date();
    
    logInfo("registry.loaded_at_startup", {
      groups: cachedRegistry.groups?.length || 0,
      commands: cachedRegistry.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0,
      version: cachedRegistry.version,
      timestamp: registryLoadTime.toISOString()
    });
    
    return cachedRegistry;
  } catch (error) {
    logError("registry.load_failed", error);
    throw new Error(`Failed to load command registry: ${error.message}`);
  }
}

/**
 * Get the currently cached registry
 */
export function getRegistryFromCache() {
  if (!cachedRegistry) {
    throw new Error("Registry not loaded. Call loadRegistryAtStartup() first.");
  }
  return cachedRegistry;
}

/**
 * Refresh registry from Core's catalog endpoint
 * Supports ETag-based conditional requests
 */
export async function refreshRegistryFromCore(adapterClient, guildId) {
  try {
    const response = await adapterClient.request(guildId, {
      method: "GET",
      path: "/api/integrations/discord/catalog",
      headers: etag ? { "If-None-Match": etag } : {}
    });

    if (response.status === 304) {
      // Not modified
      logInfo("registry.refresh_not_modified", {
        etag,
        timestamp: new Date().toISOString()
      });
      return cachedRegistry;
    }

    if (response.status !== 200) {
      throw new Error(`Core returned ${response.status}`);
    }

    const newRegistry = response.data;
    
    // Update ETag if provided
    if (response.headers?.etag) {
      etag = response.headers.etag;
    }

    cachedRegistry = newRegistry;
    registryLoadTime = new Date();

    logInfo("registry.refreshed_from_core", {
      groups: newRegistry.groups?.length || 0,
      commands: newRegistry.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0,
      version: newRegistry.version,
      etag: etag || "none",
      timestamp: registryLoadTime.toISOString()
    });

    return newRegistry;
  } catch (error) {
    logError("registry.refresh_failed", error);
    throw new Error(`Failed to refresh registry from Core: ${error.message}`);
  }
}

/**
 * Convert registry format to Discord slash command format
 * Used by buildDuneCommand() Phase 3 integration
 */
export function registryToDiscordFormat(registry) {
  if (!registry || !registry.groups) {
    return { toJSON: () => [] };
  }

  const commands = [];

  for (const group of registry.groups) {
    const subcommands = (group.subcommands || []).map((sc) => ({
      name: sc.name.toLowerCase().replace(/\s+/g, "-"),
      description: sc.description || "No description",
      options: (sc.params || []).map((param) => ({
        name: param.name.toLowerCase(),
        description: param.description || "Parameter",
        type: 3, // STRING type
        required: param.required !== false
      }))
    }));

    if (subcommands.length > 0) {
      commands.push({
        name: group.name.toLowerCase(),
        description: group.title || "Command group",
        type: 1, // CHAT_INPUT
        options: subcommands.map((sc) => ({
          name: sc.name,
          description: sc.description,
          type: 1, // SUBCOMMAND
          options: sc.options
        }))
      });
    }
  }

  return {
    toJSON: () => commands
  };
}

/**
 * Get registry metadata (load time, ETag, etc.)
 */
export function getRegistryMetadata() {
  return {
    loadTime: registryLoadTime,
    version: cachedRegistry?.version,
    groups: cachedRegistry?.groups?.length || 0,
    etag,
    commandCount: cachedRegistry?.groups?.reduce((sum, g) => sum + (g.subcommands?.length || 0), 0) || 0
  };
}

